export const RESET_STORE = 'RESET_STORE';
export const SET_SAFE_AREA_INTENT = 'SET_SAFE_AREA_INTENT';
export const START_LOADING = 'START_LOADING';
export const API_WAITING_TIME = 'API_WAITING_TIME';
export const SET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_USER_OTHER_DETAIL = 'SET_USER_OTHER_DETAIL';
export const CUSTOM_POPUP = 'CUSTOM_POPUP';
export const EVENT_DATA = 'EVENT_DATA';
