require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'mobile_app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  #pod 'react-native-cookies', :path => '../node_modules/react-native-cookies'

  pod 'ReactNativeMoEngage', :path => '../node_modules/react-native-moengage'
  pod 'MoEngage-iOS-SDK'

  target 'mobile_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

#  post_install do |installer|
#    react_native_post_install(installer)
#  end
  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        end
      end
    end
end
